__title__ = 'feng'
__version__ = '0.2.1'
__author__ = 'Alexander Svanevik, Anders Aagard, Mats Julian Olsen'
__license__ = 'MIT'
__copyright__ = 'Copyright 2016 Alexander Svanevik, Anders Aagard, Mats Julian Olsen'
